#include "PalBaseCampModuleObjectMaintenance_ExtinguishFire.h"

UPalBaseCampModuleObjectMaintenance_ExtinguishFire::UPalBaseCampModuleObjectMaintenance_ExtinguishFire() {
}

void UPalBaseCampModuleObjectMaintenance_ExtinguishFire::OnTriggerByReachAccumulateTriggerValue(UPalMapObjectModelEffect_AccumulateTrigger* Effect_AccumulateTrigger, UPalMapObjectModel* OwnerModel) {
}


