#include "PalGuildEnterRequestSequence_ConfirmLoseBaseCampToApplicantPlayer.h"

UPalGuildEnterRequestSequence_ConfirmLoseBaseCampToApplicantPlayer::UPalGuildEnterRequestSequence_ConfirmLoseBaseCampToApplicantPlayer() {
}


