#include "PalMapObjectMedicalPalBedSleepOnSideLocationOffsetComponent.h"

UPalMapObjectMedicalPalBedSleepOnSideLocationOffsetComponent::UPalMapObjectMedicalPalBedSleepOnSideLocationOffsetComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


