#include "PalMapObjectBaseCampPassiveEffectWorkHardParameterComponent.h"

UPalMapObjectBaseCampPassiveEffectWorkHardParameterComponent::UPalMapObjectBaseCampPassiveEffectWorkHardParameterComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


