#include "PalMapObjectBaseCampPassiveEffectWorkHardParameterComponent.h"

UPalMapObjectBaseCampPassiveEffectWorkHardParameterComponent::UPalMapObjectBaseCampPassiveEffectWorkHardParameterComponent() {
}

