#include "PalMapObjectBaseCampPassiveEffectParameterComponentBase.h"

UPalMapObjectBaseCampPassiveEffectParameterComponentBase::UPalMapObjectBaseCampPassiveEffectParameterComponentBase(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


