#include "PalUIMapObjectEnergyStatusIndicatorModel_GenerateEnergy.h"

UPalUIMapObjectEnergyStatusIndicatorModel_GenerateEnergy::UPalUIMapObjectEnergyStatusIndicatorModel_GenerateEnergy() {
}

void UPalUIMapObjectEnergyStatusIndicatorModel_GenerateEnergy::OnUpdateStoredEnergyAmount(UPalMapObjectGenerateEnergyModel* GenerateEnergyModel) {
}


