#include "PalUIMapObjectEnergyStatusIndicatorParameter_GenerateEnergy.h"

UPalUIMapObjectEnergyStatusIndicatorParameter_GenerateEnergy::UPalUIMapObjectEnergyStatusIndicatorParameter_GenerateEnergy() {
}


