#pragma once
#include "CoreMinimal.h"
#include "EPalMapObjectOperationResult.generated.h"

UENUM(BlueprintType)
enum class EPalMapObjectOperationResult : uint8 {
    None,
    Canceled,
    FailedInUnderRaidPVP,
    FailedInLimitVolume,
    FailedInDungeon,
    FailedOverflowBaseCampNumInGuild,
    FailedOverflowBaseCampNumInWorld,
    FailedTooNearOtherBaseCampArea,
    FailedOtherGuildBaseCampArea,
    FailedOtherGuildBaseCampAreaPaint,
    FailedExceedMaxZ,
    FailedUnderOceanPlane,
    FailedCannotInstallNotInDoor,
    FailedCannotInstallNotOnBase,
    FailedNotExistsReplaceTarget,
    FailNotFoundBaseCampWorkerDirectorBelongTo,
    FailedNotEnoughMaterials,
    FailedInValidWeakSelf,
    FailedInValidRequestHandler,
    FailedCannotDismantleNotAuthenticatedPasswordLock,
    FailedCannotDismantleLockedPrivateByNotLocalPlayer,
    FailedNotReady,
    FailNotFoundClass,
    FailLackSupportedLevel,
    FailNotConnectToOther,
    FailedNotInstallOnBackground,
    FailOverlap,
    FailedIntersectOtherObject,
    FailNotAttachToWall,
    FailNotAttachToCeil,
    FailNotFoundBuildObjectData,
    FailNotAvailableBaseCampBelongTo,
    FailNotFoundBaseCampBelongTo,
    FailSpawnNotFoundBaseCampBelongTo,
    FailedExceedMaxNumInBaseCamp,
    FailedNotExistsItemProviderPlaceOn,
    FailedNotFoundModel,
    FailedNotBuildObject,
    FailedNotFoundBuildProcess,
    FailedNotBuildingState,
    FailNotFoundRequestPlayerPalStorage,
    FailNotEnoughPalBoxEmptySlot,
    FailedNotInstallBySurface,
    FailedTooSteepSlopeAngle,
    FailedAccessPointCannotGrounded,
    FailedChestCannotGrounded,
    FailedNotCanDismantleState,
    FailedNotExistRequestPlayer,
    FailedNotCanPaintState,
    FailedBuildingLimit,
    FailedCannotInstallInRaidBossArea,
    FailedExceedMaxBuildCountInRaidBossArea,
    FailedCannotInstallOutOfBaseCampInRaidBossArea,
    FailedPlayerCannotSpawn,
    Success,
};

