#pragma once
#include "CoreMinimal.h"
#include "EPalBuildObjectTypeForUIDisplay.generated.h"

UENUM(BlueprintType)
enum class EPalBuildObjectTypeForUIDisplay : uint8 {
    Invalid,
    Product_Repair,
    Weapon,
    Refine,
    Medicine,
    Deforest_Mining,
    FishingPond,
    PalCaptureItem,
    PalManagement,
    PalTraining,
    PalWork,
    PalBreeding,
    PalOther,
    Chest,
    StorageFurniture,
    Cooking,
    FeedBox,
    Farm,
    Bed,
    GenerateElectricity,
    Electricity,
    Spa,
    Health,
    Freestanding,
    WallHanging,
    Ceiling,
    Wood,
    Stone,
    Metal,
    Glass,
    JapaneseStyle,
    Clean,
    Trap,
    Interception,
    Barieer,
    EfficiencEnhancement,
    SignBoard,
    FleaMarket,
    Statue,
    Raid,
    Desk,
    Chair,
    Carpet,
    WallDecoration,
    Houseplants,
    Flag,
    Milling_Crusher,
    Ornament,
    Other,
};

