#pragma once
#include "CoreMinimal.h"
#include "EPalMapObjectDestroyFXType.generated.h"

UENUM(BlueprintType)
enum class EPalMapObjectDestroyFXType : uint8 {
    None,
    Normal,
    NormalWood,
    NormalRock,
    NormalMetal,
    FoliageTree,
    Pickup,
    Pickup_Wood,
    Pickup_Stone,
    Pickup_Berry,
    LowTree,
    Rock,
    FoliageTree_CherryBlossom,
    Mushroom,
    Glass,
    FoliageTree_Red,
    FoliageTree_Yellow,
    FoliageTree_Pink,
    FoliageTree_Dead,
    FoliageTree_Snow,
    Blueprint_BuildCancel,
    DestroyableWall_Rock01,
    DestroyableWall_Rock02,
    Pot,
    LifeCrystal,
    Reserved001,
    Reserved002,
    Reserved003,
    Reserved004,
    Reserved005,
    Reserved006,
    Reserved007,
    Reserved008,
    Reserved009,
    Reserved010,
    Reserved011,
    Reserved012,
    Reserved013,
    Reserved014,
    Reserved015,
    Reserved016,
    Reserved017,
    Reserved018,
    Reserved019,
    Reserved020,
};

