#pragma once
#include "CoreMinimal.h"
#include "EPalVisualEffectID.generated.h"

UENUM(BlueprintType)
enum class EPalVisualEffectID : uint8 {
    None,
    CaptureEmissive,
    SpawnFromBallEmissive,
    ReturnToBallEmissive,
    FadeOut,
    FadeIn,
    PalOutlineFadeIn,
    PalOutlineFadeOut,
    PalBattleOutline,
    Poison,
    PowerUp,
    DeadEffect,
    FireCondition,
    WaterCondition,
    IceCondition,
    ElectricityCondition,
    EarthCondition,
    LeafCondition,
    DarkCondition,
    Swimming,
    CameraVignette,
    PalEffectFadeIn,
    PalEffectFadeOut,
    RarePal,
    FunnelStartEmissive,
    FunnelEndEmissive,
    SelfDestructEmissive,
    Mosaic,
    ChangeElement_Ice,
    ChangeElement_Normal,
    ChangeElement_Fire,
    ChangeElement_Water,
    ChangeElement_Leaf,
    ChangeElement_Electricity,
    ChangeElement_Earth,
    ChangeElement_Dark,
    ChangeElement_Dragon,
    DebugRefresh,
};

