#pragma once
#include "CoreMinimal.h"
#include "EPalItemTypeB.generated.h"

UENUM(BlueprintType)
enum class EPalItemTypeB : uint8 {
    None,
    WeaponMelee,
    WeaponBow,
    WeaponCrossbow,
    WeaponHandgun,
    WeaponAssaultRifle,
    WeaponSniperRifle,
    WeaponRocketLauncher,
    WeaponShotgun,
    WeaponFlameThrower,
    WeaponGatlingGun,
    WeaponCollectionTool,
    WeaponThrowObject,
    WeaponGrapplingGun,
    SPWeaponCaptureBall,
    SPWeaponDamageTrap,
    SPWeaponCaptureTrap,
    SPWeaponCaptureRope,
    ArmorHead,
    ArmorBody,
    Accessory,
    MaterialOre,
    MaterialJewelry,
    MaterialIngot,
    MaterialWood,
    MaterialStone,
    MaterialProccessing,
    MaterialMonster,
    MaterialPalEgg,
    ConsumeBandage,
    ConsumeSeed,
    ConsumeBullet,
    ConsumeWazaMachine,
    ConsumeTechnologyBook,
    ConsumeAncientTechnologyBook,
    ConsumeOther,
    ConsumeGainStatusPoints,
    ConsumePalLevelUp,
    ConsumePalGainExp,
    ConsumePalTalentUp,
    ConsumePalRankUp,
    FoodMeat,
    FoodVegetable,
    FoodFish,
    FoodDishMeat,
    FoodDishVegetable,
    FoodDishFish,
    FoodProcessed,
    Essential,
    Essential_UnlockPlayerFuture,
    Glider,
    Shield,
    Money,
    Medicine,
    Drug,
    MonsterEquipWeapon,
    Blueprint,
    ReturnToBaseCamp,
    Essential_PalGear,
};

